Candidate_Portal_Auth/Controllers/CandidatesController.cs
using Candidate_Portal_Auth.Data;
using Candidate_Portal_Auth.Models;
using Candidate_Portal_Auth.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MasterDetailOperation.Controllers
{
    public class CandidatesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _he;
        public CandidatesController(ApplicationDbContext context, IWebHostEnvironment he)
        {
            this._context = context;
            this._he = he;
        }
        public async Task<IActionResult> Index()
        {

            return View(await _context.Candidates.Include(x => x.CandidateSkills).ThenInclude(y => y.Skill).ToListAsync());
        }
        public IActionResult AddNewSkills(int? id)
        {
            ViewBag.skill = new SelectList(_context.Skills, "SkillId", "SkillName", id.ToString() ?? "");
            return PartialView("_addNewSkills");
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CandidateVM candidateVM, int[] skillId)
        {
            if (ModelState.IsValid)
            {
                Candidate candidate = new Candidate()
                {
                    CandidateName = candidateVM.CandidateName,
                    DateOfBirth = candidateVM.DateOfBirth,
                    Phone = candidateVM.Phone,
                    Fresher = candidateVM.Fresher
                };
                //Image
                var file = candidateVM.ImagePath;
                string webroot = _he.WebRootPath;
                string folder = "Images";
                string imgFileName = Path.GetFileName(candidateVM.ImagePath.FileName);
                string fileToSave = Path.Combine(webroot, folder, imgFileName);

                if (file != null)
                {
                    using (var stream = new FileStream(fileToSave, FileMode.Create))
                    {
                        candidateVM.ImagePath.CopyTo(stream);
                        candidate.Image = "/" + folder + "/" + imgFileName;
                    }
                }

                foreach (var item in skillId)
                {
                    CandidateSkill candidateSkill = new CandidateSkill()
                    {
                        Candidate = candidate,
                        CandidateId = candidate.CandidateId,
                        SkillId = item
                    };
                    _context.CandidateSkills.Add(candidateSkill);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public async Task<IActionResult> Edit(int? id)
        {
            var candidate = await _context.Candidates.FirstOrDefaultAsync(x => x.CandidateId == id);

            CandidateVM candidateVM = new CandidateVM()
            {
                CandidateId = candidate.CandidateId,
                CandidateName = candidate.CandidateName,
                DateOfBirth = candidate.DateOfBirth,
                Phone = candidate.Phone,
                Image = candidate.Image,
                Fresher = candidate.Fresher
            };
            var existSkill = _context.CandidateSkills.Where(x => x.CandidateId == id).ToList();
            foreach (var item in existSkill)
            {
                candidateVM.SkillList.Add(item.SkillId);
            }
            return View(candidateVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CandidateVM candidateVM, int[] skillId)
        {
            if (ModelState.IsValid)
            {
                Candidate candidate = new Candidate()
                {
                    CandidateId = candidateVM.CandidateId,
                    CandidateName = candidateVM.CandidateName,
                    DateOfBirth = candidateVM.DateOfBirth,
                    Phone = candidateVM.Phone,
                    Fresher = candidateVM.Fresher,
                    Image = candidateVM.Image
                };
                var file = candidateVM.ImagePath;
                if (file != null)
                {
                    string webroot = _he.WebRootPath;
                    string folder = "Images";
                    string imgFileName = Path.GetFileName(candidateVM.ImagePath.FileName);
                    string fileToSave = Path.Combine(webroot, folder, imgFileName);
                    using (var stream = new FileStream(fileToSave, FileMode.Create))
                    {
                        candidateVM.ImagePath.CopyTo(stream);
                        candidate.Image = "/" + folder + "/" + imgFileName;
                    }
                }
                
                var existSkill = _context.CandidateSkills.Where(x => x.CandidateId == candidate.CandidateId).ToList();
                foreach (var item in existSkill)
                {
                    _context.CandidateSkills.Remove(item);
                }
                foreach (var item in skillId)
                {
                    CandidateSkill candidateSkill = new CandidateSkill()
                    {
                        
                        CandidateId = candidate.CandidateId,
                        SkillId = item
                    };
                    _context.CandidateSkills.Add(candidateSkill);
                }
                _context.Update(candidate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
    }
}

Candidate_Portal_Auth/Views/Candidates/Create.cshtml
@model Candidate_Portal_Auth.Models.ViewModels.CandidateVM
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col">
        <h2 class="display-5">Add New Candidate</h2>
        <form asp-action="Create" asp-controller="Candidates" enctype="multipart/form-data" method="post">
            <div class="row">
                <div class="col-6">
                    <div class="row mb-2">
                        <label asp-for="CandidateName" class="col-form-label col-3"></label>
                        <div class="col-6">
                            <input asp-for="CandidateName" class="form-control form-control-sm" />
                        </div>
                        <div class="col-3">
                            <span asp-validation-for="CandidateName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <label asp-for="DateOfBirth" class="col-form-label col-3"></label>
                        <div class="col-6">
                            <input asp-for="DateOfBirth" class="form-control form-control-sm" type="date" />
                        </div>
                        <div class="col-3">
                            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <label asp-for="Phone" class="col-form-label col-3"></label>
                        <div class="col-6">
                            <input asp-for="Phone" class="form-control form-control-sm" type="number" />
                        </div>
                        <div class="col-3">
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <label asp-for="ImagePath" class="col-form-label col-3"></label>
                        <div class="col-6">
                            <input asp-for="ImagePath" class="form-control form-control-sm" type="file" />
                        </div>
                        <div class="col-3">
                            <span asp-validation-for="ImagePath" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <label asp-for="Fresher" class="col-form-label col-3"></label>
                       <div class="col-6 mt-2">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="Fresher" />
                            </label>
                       </div>
                    </div>
                </div>
                <div class="col-6">
                    <h5>Select Skill</h5>
                    <div class="d-flex justify-content-end">
                        <a id="btnPlus" class="btn btn-success"><i class="fa fa-plus"></i></a>
                    </div>
                    <div id="skillContainer">
                        <script>
                            LoadData();
                        </script>
                    </div>
                </div>
            </div>
            <div class="row mb-2">
              <div class="d-flex justify-content-end">
                    <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Save</button>
              </div>
            </div>
        </form>
    </div>
</div>

Candidate_Portal_Auth/Views/Candidates/Edit.cshtml
@model Candidate_Portal_Auth.Models.ViewModels.CandidateVM
@{
    ViewData["Title"] = "Edit";
}
<div class="row">
    <div class="col">
        <h2 class="display-5">Edit Candidate</h2>
        <form asp-action="Edit" asp-controller="Candidates" enctype="multipart/form-data" method="post">
            <div class="row">
                <div class="col-6">
                    <input asp-for="CandidateId" type="hidden"/>
                    <input asp-for="Image" type="hidden"/>
                    <div class="row mb-2">
                        <label asp-for="CandidateName" class="col-form-label col-3"></label>
                        <div class="col-6">
                            <input asp-for="CandidateName" class="form-control form-control-sm" />
                        </div>
                        <div class="col-3">
                            <span asp-validation-for="CandidateName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <label asp-for="DateOfBirth" class="col-form-label col-3"></label>
                        <div class="col-6">
                            <input asp-for="DateOfBirth" class="form-control form-control-sm" type="date" />
                        </div>
                        <div class="col-3">
                            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <label asp-for="Phone" class="col-form-label col-3"></label>
                        <div class="col-6">
                            <input asp-for="Phone" class="form-control form-control-sm" />
                        </div>
                        <div class="col-3">
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <label asp-for="ImagePath" class="col-form-label col-3"></label>
                        <div class="col-6"> 
                            <input asp-for="ImagePath" class="form-control form-control-sm" type="file" />
                            <img class="rounded-circle" src="@Model.Image" width="32">
                        </div>
                        <div class="col-3">
                            <span asp-validation-for="ImagePath" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <label asp-for="Fresher" class="col-form-label col-3"></label>
                        <div class="col-6 mt-2">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="Fresher" />
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <h5>Select Skill</h5>
                    <div class="d-flex justify-content-end">
                        <a id="btnPlus" class="btn btn-success"><i class="fa fa-plus"></i></a>
                    </div>
                    <div id="skillContainer">
                        @foreach (var item in Model.SkillList)
                        {
                            <script>
                                LoadData(@item)
                            </script>
                        }
                    </div>
                </div>
            </div>
            <div class="row mb-2">
                <div class="d-flex justify-content-end">
                    <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Update</button>
                </div>
            </div>
        </form>
    </div>
</div>

Candidate_Portal_Auth/Views/Candidates/Index.cshtml
@model IEnumerable<Candidate_Portal_Auth.Models.Candidate>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col">
        <h2 class="display-4">Candidate List</h2>
        <div class="d-flex justify-content-end">
            <a asp-action="Create" asp-controller="Candidates" class="btn btn-outline-primary btn-sm mb-2"><i class="fa fa-plus-square"></i> Add New Candidate</a>
        </div>
        @foreach (var item in Model)
        {
            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between">
                    <div>
                        <img class="rounded-circle" src="@item.Image" width="32"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <b>Name :</b> @Html.DisplayFor(x=>item.CandidateName)
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <b>Date of Birth :</b> @Html.DisplayFor(x=>item.DateOfBirth)
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <b>Phone :</b> @Html.DisplayFor(x=>item.Phone)
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <b>Fresher :</b> @Html.DisplayFor(x=>item.Fresher)
                    </div>
                    <div>
                        <a asp-action="Edit" asp-controller="Candidates" asp-route-id="@item.CandidateId" class="btn btn-outline-success btn-sm"><i class="fa fa-edit"></i></a>&nbsp;&nbsp;
                        <a asp-action="Delete" asp-controller="Candidates" asp-route-id="@item.CandidateId" class="btn btn-outline-danger btn-sm"><i class="fa fa-trash"></i></a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-striped table-responsive-sm">
                        <thead class="table-primary fw-bold">
                            <tr>
                                <th>Skills</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var i in item.CandidateSkills)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(x=>i.Skill.SkillName)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        }
    </div>
</div>

Candidate_Portal_Auth/Views/Candidates/_addNewSkills.cshtml
@model Candidate_Portal_Auth.Models.Skill
<div class="row mb-2 d-flex justify-content-between">
    <div class="col-10">
        @Html.DropDownListFor(x=>x.SkillId,ViewBag.skill as SelectList,"-----Select-----",new{@class="form-control"})
    </div>
    <div class="col-2">
        <a id="deleteSkill" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
    </div>
</div>